### ISSUE TITLE
Improvement Request: Modification to get SVG preview working on the Origin

### ISSUE THREAD

**Issue by mrcg** [HBehrens/fixup_shaper_svg#2]
The current script (fixup_shaper_svg.py) is working as such.
Converted SVG files can be used and inserted on Origin.
However the SVG image preview is not working.

Reason for this is that in the output file the following information will be added:
encoding='cp1252'

When removing the encoding statement the file can be used on the Origin and the SVG preview is also working.
Would be great if someone could update the python script to remove "encoding='cp1252'" to finally get preview working.
Unfortunately i do not have enough python skills to do this on my own. ;-)

**Comment by HBehrens** [comment]
Thank you, @mrcg – do you think you can provide your original file as an attachment? I believe your description is sufficient, but testing against the actually failing file and proving it working after adjusting the script would be better?

**Comment by mrcg** [comment]
Hello! Many thanks for your reply !!!
Attached the original files for your reference.

![Github_fixup_shaper_svg_001](https://github.com/HBehrens/fixup_shaper_svg/assets/4404991/08a7dec1-b457-4586-bceb-ca32ddebea37)

![01_Box_Rund_FreeCAD_infile](https://github.com/HBehrens/fixup_shaper_svg/assets/4404991/3eb32cb5-c439-4cb7-b77a-f32626e7755f)

![02_Box_Rund_FixupShaperScript_outfile](https://github.com/HBehrens/fixup_shaper_svg/assets/4404991/1026ed3c-1304-4fdb-ac40-4ac21850e727)

![03_Box_Rund_FixupShaperScript_EncodingDeletedManually](https://github.com/HBehrens/fixup_shaper_svg/assets/4404991/cde7b41a-db87-4ea0-a6a3-1679d94d1f92)

Would be great to get file support and image preview finally working on the Origin.

**Comment by mrcg** [comment]
Here all the files in one zip file:
[SVG.zip](https://github.com/HBehrens/fixup_shaper_svg/files/15051944/SVG.zip)

**Comment by HBehrens** [comment]
@mrcg could you manually double check if this fixes your issue? I tried to capture this via automated tests for Linux, macOS, and Windows for Python 3.8 and 3.11, but I don't have convenient access to a windows box and would rather see someone using it for real.

Thank you!
